apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "{{ ti.task_id }}-{{ ds_nodash }}-{{ ti.try_number }}"
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: ~
  imagePullPolicy: IfNotPresent
  mainClass: com.sirclo.spark.job.BigqueryToParquet
  mainApplicationFile: "local:///opt/app/spark/target/scala-2.12/Spark_2.12_3.3.2_1.0.0-RELEASE.jar"
  sparkVersion: "3.3.2"
  restartPolicy:
    type: Never
  timeToLiveSeconds: 300
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    labels:
      version: 3.3.2
    serviceAccount: spark-spark
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: cattle
    secrets:
      - name: spark-gcp
        path: /mnt/secrets
        secretType: GCPServiceAccount
  executor:
    cores: 1
    instances: 1
    memory: "1g"
    labels:
      version: 3.3.2
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: cattle
    secrets:
      - name: spark-gcp
        path: /mnt/secrets
        secretType: GCPServiceAccount
  nodeSelector:
    lifecycle: cattle
  dynamicAllocation:
    enabled: True
    initialExecutors: 1
    minExecutors: 1
    maxExecutors: 3
