apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "{{ task.task_id }}-{{ ds_nodash }}"
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "andresitorusz/spark:3.3.2-scala2.12.15-openjdk17.0.7"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/bitnami/spark/examples/jars/spark-examples_2.12-3.3.2.jar"
  sparkVersion: "3.3.2"
  restartPolicy:
    type: Never
  timeToLiveSeconds: 30
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.3.2
    serviceAccount: spark-spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.3.2