dag:
  name: bronze_school.student
  behavior:
    schedule_interval: 1 * * * *
    start_date: 2023, 6, 14
    depends_on_past: True
    catch_up: False
    retry:
      count: 4
      delay_in_minute: 1
  tags:
    - mysql
    - bigquery
    - truncate
  owner: data.engineer@sirclo.com
task:
  type: mysql_to_bq
  source: 
    connection: mysql_school
  target:
    bq:
      project:
      dataset:
      table:
      write_disposition:
    gcs:
      project:
      bucket: