dag:
  name: bronze_school.student
  behavior:
    schedule: 1 * * * *
    start_date: 2023, 6, 14
    depends_on_past: True
    catch_up: False
    retry:
      count: 4
      delay_in_minute: 1
  tags:
    - mysql
    - bigquery
    - truncate
  owner: data.engineer@sirclo.com
  priority_weight: 1
task:
  type: mysql_to_bq
  source:
    connection: mysql_school
    schema: school
    table: student
    timestamp_keys:
      - created_at
      - updated_at
    unique_keys:
      - id
  target:
    bq:
      project: pocz-389704
      dataset: bronze_school
      table: student
      write_disposition: WRITE_APPEND
      partitioned_keys:
    gcs:
      project:
      bucket: