database:
  name: school
  table: student
  type: mysql
  connection: mysql_school
dag:
  behavior:
    schedule: 1 * * * *
    start_date: 2023, 6, 10
    depends_on_past: True
    catch_up: False
    retry:
      count: 4
      delay: 1
    email_on_failure: False
    email_on_retry: False
    max_active_tasks: 1
  tags:
    - mysql
    - bigquery
    - truncate
  type:
    - bronze
    - mysql_to_bq
  owner: data.engineer@sirclo.com
  email:
    - data.engineer@sirclo.com
gcp:
  gcs:
    project:
    bucket:
  bq:
    project:
    dataset:
    write_disposition:
schema:
  - name: "id"
    type: "STRING"
    mode: "NULLABLE"
  - name: "name"
    type: "STRING"
    mode: "NULLABLE"
  - name: "created_at"
    type: "TIMESTAMP"
    mode: "NULLABLE"
  - name: "update_at"
    type: "TIMESTAMP"
    mode: "NULLABLE"